{"errorMessage": "sndfile library not found", "errorType": "OSError", "stackTrace": ["  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n", "  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n", "  File \"<frozen importlib._bootstrap>\", line 702, in _load\n", "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n", "  File \"/var/task/app.py\", line 9, in <module>\n    from preprocessor import make_specgram, transform_img, mixing_audios\n", "  File \"/var/task/preprocessor.py\", line 1, in <module>\n    import librosa\n", "  File \"/var/task/librosa/__init__.py\", line 211, in <module>\n    from . import core\n", "  File \"/var/task/librosa/core/__init__.py\", line 6, in <module>\n    from .audio import *  # pylint: disable=wildcard-import\n", "  File \"/var/task/librosa/core/audio.py\", line 8, in <module>\n    import soundfile as sf\n", "  File \"/var/task/soundfile.py\", line 142, in <module>\n    raise OSError('sndfile library not found')\n"]}